on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    strategy:
      matrix:
        node: ["14", "16"]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Github repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install NPM Packages
        run: yarn install

  static-code-analysis:
    needs: dependencies
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    strategy:
      matrix:
        node: ["14", "16"]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Github repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install NPM Packages
        run: yarn install
      - name: TS Standard
        run: yarn ts-standard

  test:
    runs-on: ubuntu-latest
    needs: dependencies
    env:
      NODE_ENV: test

    strategy:
      matrix:
        node: ["14", "16"]
        mongo: ["3-xenial", "4-focal", "5-focal"]
    services:
      db:
        image: mongo:${{ matrix.mongo }}
        ports: ["27017:27017"]
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.8

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Github repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install NPM Packages
        run: yarn install
      - name: Test
        run: yarn test --coverage
      - name: LibreCov Node (PR)
        if: ${{ github.event_name == 'pull_request' && matrix.node == '14' && matrix.mongo == '3-xenial' }}
        env:
          CODECOV_URL: ${{ secrets.LIBRECOV_ENDPOINT }}
          CODECOV_TOKEN: ${{ secrets.LIBRECOV_TOKEN }}
          REAL_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_RUN_ID: "1${{ github.run_id }}"
        run: |
          yarn add codecov
          npx codecov --commit=$REAL_SHA  --disable=s3
      - name: LibreCov Node (Push)
        if: ${{ github.event_name == 'push' && matrix.node == '14' && matrix.mongo == '3-xenial' }}
        env:
          CODECOV_URL: ${{ secrets.LIBRECOV_ENDPOINT }}
          CODECOV_TOKEN: ${{ secrets.LIBRECOV_TOKEN }}
          GITHUB_RUN_ID: "1${{ github.run_id }}"
        run: |
          yarn add codecov
          npx codecov --disable=s3